Fix code smells in appropriate files #1115
ita-social-projects/horondi_admin pull request #1141
Opened 2021-12-09 23:40 UTC by ostgit12

## Description
According to task I fixed all code smells in files:
1) form-regexp.js Simplify regular expression to less than 20 symbols (fields: onlyPositiveFloat, phoneNumber);
2) home-page.test.js Correct assertion rule "Component should exist"
3) login-page.test.js Correct assertion rule "Should exist"

### Checklist

- [ x ] 🔽 My branch is up-to-date with "development" branch
- [ x ] ✅ All tests passed locally
- [ x ] ✨ My changes working with up-to-date front-end and back-end part locally, like charm
- [ x ] 🔗 Link pull request to issue

2021-12-21 13:26 UTC, byavdoshniak approved these changes

2022-01-21 07:56 UTC, maarekua approved these changes

2022-02-02 07:58 UTC, maarekua requested changes

2022-02-02 07:58 UTC, maarekua commented on src/pages/home-page/tests/home-page.test.js
> +    expect(wrapper.find('LoadingBar').length).toEqual(0);
The title is "Should display loading bar", but you are expecting that length of the elements to equal 0...

2022-03-23 20:16 UTC, closed without merging