Feature/957/promocodes
ita-social-projects/horondi_admin pull request #1171
Opened 2022-01-11 22:54 UTC by bohdanst1914

Implemented promo code feature:

- created a component for a list of all promo codes
- created  a component for creating a promo code has been created
- created queries for getAllPromoCodes, addPromoCodes, deletePromoCodeByID
- created tests for both components that were created

### Checklist

- [ ] 🔽 My branch is up-to-date with "development" branch
- [ ] ✅ All tests passed locally
- [ ] ✨ My changes working with up-to-date front-end and back-end part locally, like charm
- [ ] 🔗 Link pull request to issue

2022-01-17 15:40 UTC, maarekua requested changes

2022-01-17 15:40 UTC, maarekua commented on src/components/nav-menu/nav-menu.js
> +    returnedList(category[0], category[1], category[2], classes.nested)
category[0], category[1], category[2]

I cant even imagine what it is :).

2022-01-17 15:40 UTC, maarekua commented on src/pages/promo-code/promo-code-add/promo-code-add.js
> +            onChange={(event) =>
Move out all eventHandlers from JSX.

2022-01-20 21:13 UTC, bohdanst1914 commented on src/pages/promo-code/promo-code-add/promo-code-add.js
> +            onChange={(event) =>
fixed

2022-01-24 11:51 UTC, maarekua approved these changes

2022-01-24 11:53 UTC, tarasSanotskyi approved these changes

2022-01-24 11:53 UTC, merged