Feature/1197/add table on about material page
ita-social-projects/horondi_admin pull request #1200
Opened 2022-01-24 17:42 UTC by OlehProtsak

## Description

Create a table for front-end part of "About Material" page with static data.

#### Screenshots

|         Original          |             
| :-----------------------: | 
| ** 
![зображення](https://user-images.githubusercontent.com/65071268/150835099-8043e061-aad3-4d05-8c9a-e0d4a019290f.png)
** 

### Checklist

- [ ] 🔽 My branch is up-to-date with "development" branch
- [ ] ✅ All tests passed locally
- [ ] ✨ My changes working with up-to-date front-end and back-end part locally, like charm
- [ ] 🔗 Link pull request to issue

2022-01-24 19:34 UTC, Skrekliam requested changes

2022-01-24 19:34 UTC, Skrekliam commented on src/pages/material/material-about.js
> -        id='add-materials'
Please use camel case

2022-01-24 19:34 UTC, Skrekliam commented on src/pages/material/material-about.js
> +          data-cy='main-header'
Here the same

2022-01-24 19:39 UTC, OlehProtsak commented on src/pages/material/material-about.js
> +          data-cy='main-header'
fixed

2022-01-24 19:39 UTC, OlehProtsak commented on src/pages/material/material-about.js
> -        id='add-materials'
fixed

2022-01-25 10:12 UTC, maarekua approved these changes

2022-01-25 10:40 UTC, Skrekliam approved these changes

2022-01-25 10:42 UTC, merged