fixed error text color
ita-social-projects/horondi_admin pull request #1260
Opened 2022-03-18 22:17 UTC by Yevhendzyuba

## Description

Fixed error color from black to red in pocket constructor.

#### Screenshots

|         Original          |         Updated          |
| :-----------------------: | :----------------------: |
| ** ![зображення](https://user-images.githubusercontent.com/56231198/159091717-a257e587-b849-4df2-9fa2-44155e59e3bb.png)** | ** ![зображення](https://user-images.githubusercontent.com/56231198/159091758-1e0bdf9e-0f2d-45f8-8f67-a845fe5258c4.png)** |

### Checklist

- [ ] 🔽 My branch is up-to-date with "development" branch
- [ ] ✅ All tests passed locally
- [ ] ✨ My changes working with up-to-date front-end and back-end part locally, like charm
- [ ] 🔗 Link pull request to issue

2022-03-21 14:43 UTC, afanasieva-anastasiia requested changes

2022-03-21 14:43 UTC, afanasieva-anastasiia commented on src/containers/additional-price-container/additional-price-container.styles.js
> +      color: '#e60000'
Worth using palette instead of hardcoding color of error.

2022-03-21 19:48 UTC, afanasieva-anastasiia approved these changes

2022-03-22 18:50 UTC, SirAndrii approved these changes

2022-03-23 08:19 UTC, maarekua approved these changes

2022-03-23 08:20 UTC, merged