fixed UserRole config
ita-social-projects/horondi_admin pull request #1287
Opened 2022-03-31 12:05 UTC by Pipuss

## Description

There was bad UserRoles config for use-user-tabs hook

#### Screenshots

|         Original          |         Updated          |
| :-----------------------: | :----------------------: |
| ** ![image](https://user-images.githubusercontent.com/45914032/161050606-1e62d79a-ae24-4501-a2f8-8bf858aa9bb5.png) ** | ** ![image](https://user-images.githubusercontent.com/45914032/161050639-0c17f13c-5650-44f0-b68e-a7398972cb23.png) ** |

### Checklist

- [ ] 🔽 My branch is up-to-date with "development" branch
- [ ] ✅ All tests passed locally
- [ ] ✨ My changes working with up-to-date front-end and back-end part locally, like charm
- [ ] 🔗 Link pull request to issue

2022-03-31 15:06 UTC, afanasieva-anastasiia requested changes

2022-03-31 15:06 UTC, afanasieva-anastasiia commented on src/configs/index.js
> +    { role: 'admin', label: 'Адмін' }
We need also superadmin role

2022-03-31 15:34 UTC, Pipuss commented on src/configs/index.js
> +    { role: 'admin', label: 'Адмін' }
Solved. 
Thanks for good remark

2022-04-04 11:33 UTC, maarekua approved these changes

2022-04-05 16:55 UTC, rostyslaw27 approved these changes

2022-04-06 06:52 UTC, RestingState approved these changes

2022-04-06 12:34 UTC, afanasieva-anastasiia approved these changes

2022-04-06 12:35 UTC, merged