Feature/1186/pagination in admin for promocode
ita-social-projects/horondi_admin pull request #1302
Opened 2022-04-07 09:21 UTC by anjtka333

## Description
pagination for promocode page was added 

#### Screenshots

|         Original          |         Updated          |
| :-----------------------: | :----------------------: |
| ** original screenshot ** | ** updated screenshot ** |

### Checklist

- [ ] 🔽 My branch is up-to-date with "development" branch
- [ ] ✅ All tests passed locally
- [ ] ✨ My changes working with up-to-date front-end and back-end part locally, like charm
- [ ] 🔗 Link pull request to issue

2022-04-07 17:42 UTC, rostyslaw27 commented on src/pages/promo-code/promo-code-page.js
> +        count={20}
We need promocodes count instead of 20

2022-04-11 07:54 UTC, rostyslaw27 requested changes

2022-04-11 07:54 UTC, rostyslaw27 commented on src/pages/promo-code/tests/promo-code-page.spec.js
> +];
It will probably be better if you take mocks to another file (promo-code-page.variables.js)

2022-04-11 07:54 UTC, rostyslaw27 commented on src/pages/promo-code/tests/promo-code-page.spec.js
> +const mocks2 = [
It is better to rename it to mockWithoutPromocodes or smth like that

2022-04-13 11:02 UTC, rostyslaw27 approved these changes

2022-04-13 11:02 UTC, Yevhendzyuba approved these changes

2022-04-13 11:03 UTC, merged