implemented multipurpose form for constructorItems based on bottom-form
ita-social-projects/horondi_admin pull request #1429
Opened 2022-07-28 10:21 UTC by Pipuss

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

#### Screenshots

|         Original          |         Updated          |
| :-----------------------: | :----------------------: |
| ** original screenshot ** | ** updated screenshot ** |

### Checklist

- [ ] 🔽 My branch is up-to-date with "development" branch
- [ ] ✅ All tests passed locally
- [ ] ✨ My changes working with up-to-date front-end and back-end part locally, like charm
- [ ] 🔗 Link pull request to issue

2022-07-28 13:45 UTC, RestingState requested changes

2022-07-28 13:45 UTC, RestingState commented on src/containers/constructor-form-container/constructor-form-container.js
> +      if (edit) {
Isn't this the same, but more concise?

      if (edit) {
        actionPayload.id = id;
      }

      if (editAndUpload) {
        actionPayload.image = partItemUpload;
      }

      dispatch(dispatchAction(actionPayload));

2022-07-29 07:59 UTC, maarekua commented on src/containers/constructor-form-container/constructor-form-container.js
> +      const editAndUpload = edit && partItemUpload instanceof File;
Boolean(edit && partItemUpload instanceof File)

2022-07-29 08:03 UTC, maarekua approved these changes

2022-07-29 15:13 UTC, RestingState approved these changes

2022-07-29 15:15 UTC, MickhaelSh approved these changes

2022-07-29 15:16 UTC, merged