Bug/1489/fix date to and code validations
ita-social-projects/horondi_admin pull request #1499
Opened 2022-11-08 19:38 UTC by tarasSanotskyi

fix date to and code validations

### Checklist

- [ ] 🔽 My branch is up-to-date with "development" branch
- [ ] ✅ All tests passed locally and linter has no warnings and errors
- [ ] ✨ My changes working with up-to-date front-end and back-end part locally, like charm
- [ ] 🔗 Link pull request to issue

2022-11-08 20:57 UTC, Pipuss commented on src/configs/error-messages.js
> +  DATE_TO: 'Кінцева дата повинна бути після початкової',
Isn't there a possibility to disable an unsuitable date range?

2022-11-08 22:26 UTC, LubomyrKashuba submitted a review, later dismissed

2022-11-09 07:33 UTC, Pipuss submitted a review, later dismissed

2022-11-09 08:12 UTC, Tolik170 submitted a review, later dismissed

2022-11-09 12:03 UTC, maarekua requested changes

2022-11-09 12:03 UTC, maarekua commented on src/pages/promo-code/promo-code-form/promo-code-form.js
> +                  isBefore(date, new Date().setDate(new Date().getDate() - 1))
Use moment.

2022-11-09 13:28 UTC, tarasSanotskyi commented on src/pages/promo-code/promo-code-form/promo-code-form.js
> +                  isBefore(date, new Date().setDate(new Date().getDate() - 1))
fixed

2022-11-11 13:09 UTC, maarekua approved these changes

2022-11-11 14:04 UTC, Pipuss approved these changes

2022-11-11 14:04 UTC, merged