refactored constructor
ita-social-projects/horondi_admin pull request #1500
Opened 2022-11-09 08:05 UTC by Pipuss

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

#### Screenshots

|         Original          |         Updated          |
| :-----------------------: | :----------------------: |
| ** original screenshot ** | ** updated screenshot ** |

### Checklist

- [ ] 🔽 My branch is up-to-date with "development" branch
- [ ] ✅ All tests passed locally and linter has no warnings and errors
- [ ] ✨ My changes working with up-to-date front-end and back-end part locally, like charm
- [ ] 🔗 Link pull request to issue

2022-11-09 08:17 UTC, Tolik170 approved these changes

2022-11-09 08:48 UTC, tarasSanotskyi approved these changes

2022-11-09 08:54 UTC, Tolik170 approved these changes

2022-11-09 12:01 UTC, maarekua requested changes

2022-11-09 12:01 UTC, maarekua commented on src/pages/constructor-list/constructor-list-page.js
> +  const availableList = useMemo(
array.filter((item) => !array2.some((item2) => item2.model.id === item.id))

2022-11-10 13:54 UTC, Pipuss commented on src/pages/constructor-list/constructor-list-page.js
> +  const availableList = useMemo(
Done

2022-11-11 13:10 UTC, maarekua approved these changes

2022-11-11 13:51 UTC, Tolik170 approved these changes

2022-11-11 13:52 UTC, merged