added possibility to use certificate for order
ita-social-projects/horondi_admin pull request #1514
Opened 2022-11-23 15:43 UTC by Tolik170

## Description

Added possibility to use certifiate for order.

#### Screenshots

|         Original          |         Updated          |
| :-----------------------: | :----------------------: |
| ** original screenshot ** | ** updated screenshot ** |

### Checklist

- [ ] 🔽 My branch is up-to-date with "development" branch
- [ ] ✅ All tests passed locally and linter has no warnings and errors
- [ ] ✨ My changes working with up-to-date front-end and back-end part locally, like charm
- [ ] 🔗 Link pull request to issue

2022-11-23 19:00 UTC, Pipuss approved these changes

2022-11-24 14:22 UTC, tarasSanotskyi approved these changes

2022-11-24 15:06 UTC, MickhaelSh submitted a review, later dismissed

2022-11-24 15:13 UTC, IrynaMel approved these changes

2022-11-24 16:38 UTC, Yurenko approved these changes

2022-11-25 14:04 UTC, byavdoshniak requested changes

2022-11-25 14:04 UTC, byavdoshniak commented on src/pages/order-item/tabs/add-product-form/add-product-form.js
> +        {certificateOrPromoError ? promoCodesConsts.error : ''}
change to helperText

2022-11-25 16:15 UTC, Tolik170 commented on src/pages/order-item/tabs/add-product-form/add-product-form.js
> +        {certificateOrPromoError ? promoCodesConsts.error : ''}
Changed

2022-11-28 07:56 UTC, MickhaelSh approved these changes

2022-11-28 17:46 UTC, olga-gchak approved these changes

2022-11-28 22:05 UTC, tarasSanotskyi approved these changes

2022-11-30 13:16 UTC, byavdoshniak approved these changes

2022-11-30 13:18 UTC, merged