Bug/1517/fix promocode discount
ita-social-projects/horondi_admin pull request #1523
Opened 2022-11-28 20:23 UTC by tarasSanotskyi

Fix promocode discount

### Checklist

- [ ] 🔽 My branch is up-to-date with "development" branch
- [ ] ✅ All tests passed locally and linter has no warnings and errors
- [ ] ✨ My changes working with up-to-date front-end and back-end part locally, like charm
- [ ] 🔗 Link pull request to issue

2022-11-29 08:21 UTC, IrynaMel approved these changes

2022-11-29 08:58 UTC, Tolik170 submitted a review, later dismissed

2022-11-29 13:20 UTC, Yurenko approved these changes

2022-11-30 08:30 UTC, MickhaelSh submitted a review, later dismissed

2022-11-30 13:25 UTC, byavdoshniak requested changes

2022-11-30 15:18 UTC, tarasSanotskyi commented on src/pages/promo-code/promo-code-form/promo-code-form.js
> +            InputProps={{ inputProps: { min: 0, max: 90, step: 5 } }}
fixed

2022-11-30 15:18 UTC, MickhaelSh approved these changes

2022-11-30 15:19 UTC, Tolik170 approved these changes

2022-11-30 15:34 UTC, Yevhendzyuba approved these changes

2022-11-30 18:44 UTC, byavdoshniak approved these changes

2022-11-30 19:37 UTC, merged