Fix products filters
ita-social-projects/horondi_admin pull request #199
Opened 2020-11-20 08:10 UTC by Iryna-Bzdyr

2020-11-20 08:47 UTC, moran711 commented on src/containers/image-upload-container/image-upload-container.js
>            id='upload-photo'
Why this element have id `upload-photo` if you are using photo and video upload?

2020-11-20 08:58 UTC, vasylshpak requested changes

2020-11-20 08:58 UTC, vasylshpak commented on src/translations/product.translations.js
>    ADD_PRODUCT: 'ДОДАТИ ПРОДУКТ',
`CLEAR_FILTERS: 'ОЧИСТИТИ ФІЛЬТРИ',
 ADD_PRODUCT: 'ДОДАТИ ПРОДУКТ',` 

Should those values be uppercase?

2020-11-21 09:53 UTC, nadiyafomenko commented on src/translations/product.translations.js
> +  COLORS: 'Кольори',
typo in word "гобелени"

2020-11-30 14:14 UTC, vasylshpak approved these changes
Good job!

2020-11-30 15:21 UTC, nadiyafomenko approved these changes

2020-11-30 19:00 UTC, moran711 approved these changes

2020-11-30 19:02 UTC, merged