Feature/612
ita-social-projects/horondi_admin pull request #703
Opened 2021-04-07 19:36 UTC by yuliiakucher

Fixed admin confirmation form page. Added verification for the creating superadmin. When first superadmin wants to add second superadmin, he/she should firstly enter code that he/she will receive via email. 
Also superadmin can resend the email for the confirmation.

![image](https://user-images.githubusercontent.com/61886864/113921877-3cebdb00-97ef-11eb-8342-1fadd3c8f468.png)
![image](https://user-images.githubusercontent.com/61886864/113922131-9522dd00-97ef-11eb-9a6f-172229394e1c.png)
![image](https://user-images.githubusercontent.com/61886864/113922382-e501a400-97ef-11eb-91d0-4820d453fb34.png)

### Checklist
- [ ] 🔽 My branch is up-to-date with "development" branch
- [ ] ✅All tests passed locally
- [ ] ✨My changes working with up-to-date front-end and admin part locally, like charm
- [ ] 🔗 Link pull request to issue

2021-04-08 16:29 UTC, AndriyLymych commented on src/pages/users/register-user/register-user.js
> +      is: 'superadmin',
please, don't use magic strings

2021-04-08 16:29 UTC, AndriyLymych commented on src/pages/users/register-user/register-user.js
> +      role: 'admin',
same

2021-04-08 16:29 UTC, AndriyLymych commented on src/pages/users/register-user/register-user.js
> +            {values.role !== 'admin' && (
same

2021-04-08 16:30 UTC, AndriyLymych commented on src/pages/users/register-user/register-user.js
> +                  variant='contained'
same

2021-04-08 16:30 UTC, AndriyLymych commented on src/pages/users/register-user/register-user.js
> +                  color='primary'
same

2021-04-08 16:30 UTC, AndriyLymych commented on src/pages/users/register-user/register-user.js
> +                  name='code'
same

2021-04-08 16:30 UTC, AndriyLymych commented on src/pages/users/users-details/containers/user-details-card/user-details-card.js
> +                color='primary'
same

2021-04-08 16:31 UTC, AndriyLymych commented on src/redux/users/tests/users.saga.test.js
> +      .put(push('/login'))
same

2021-04-09 10:43 UTC, AndriyLymych approved these changes

2021-04-10 16:37 UTC, twihell requested changes
When you create a new admin/superadmin and click "Створити", you can't see that your new user has been added to the general list of administrators. To see a newly added user, you have to reload the page.

1.
![create-admin](https://user-images.githubusercontent.com/14165251/114277450-e9b69a00-9a33-11eb-94de-901ee474e055.PNG)


2.
![after clicking submit](https://user-images.githubusercontent.com/14165251/114277479-05ba3b80-9a34-11eb-8461-017ede71f1c3.PNG)


3.
![reload page](https://user-images.githubusercontent.com/14165251/114277491-1b2f6580-9a34-11eb-95b2-185d5390215c.PNG)

4.
![after reload](https://user-images.githubusercontent.com/14165251/114277499-21bddd00-9a34-11eb-94c4-06c8f1cc8224.PNG)

2021-04-11 07:28 UTC, AndriyLymych approved these changes

2021-04-11 21:02 UTC, twihell approved these changes

2021-04-12 03:51 UTC, merged