Wrote Enzyme tests for "DialogWindowWrapper" component №432
ita-social-projects/horondi_admin pull request #719
Opened 2021-04-12 15:41 UTC by 100vbaSasha

Wrote Enzyme tests for DialogWindowWrapper component on admin panel

![image](https://user-images.githubusercontent.com/55619101/114415216-27dcc680-9bb8-11eb-8d85-e8eb0226b916.png)

### Checklist
- [ ✔ ] 🔽 My branch is up-to-date with "development" branch
- [ ✔ ] ✅ All tests passed locally
- [ ✔ ] ✨ My changes working with up-to-date front-end and back-end part locally, like charm
- [ ✔] 🔗 Link pull request to issue

2021-04-12 22:52 UTC, grebiniuk requested changes

2021-04-12 22:52 UTC, grebiniuk commented on src/components/dialog-window-wrapper/tests/dialog-window-wrapper.spec.js
> +const testProps = {
Move all test data into a separate file in tests folder, with ".variables.js" suffix.
This file (with tests) should have suffix ".test.js" not ".spec.js"

2021-04-12 22:56 UTC, grebiniuk commented on src/components/dialog-window-wrapper/tests/dialog-window-wrapper.spec.js
> +const testProps = {
You should show test coverage of your component as well.

2021-04-13 08:54 UTC, 100vbaSasha commented on src/components/dialog-window-wrapper/tests/dialog-window-wrapper.spec.js
> +const testProps = {
Вone, thanks

2021-04-13 19:47 UTC, grebiniuk approved these changes

2021-04-14 12:37 UTC, AndriyLymych approved these changes

2021-04-14 15:45 UTC, yuliiakucher approved these changes

2021-04-14 15:45 UTC, merged