component test
ita-social-projects/horondi_admin pull request #723
Opened 2021-04-14 15:19 UTC by AndronShermeta

## Description
I wrote an enzyme test on the CategoryDelete page on the admin panel
All test passed

#### Screenshots

![image](https://user-images.githubusercontent.com/73708298/114733218-d6654080-9d4b-11eb-9110-a678599ab882.png)

Original             |  Updated
:-------------------------:|:-------------------------:
** original screenshot **  |  ** updated screenshot **

### Checklist
- [✔] 🔽 My branch is up-to-date with "development" branch
- [✔] ✅ All tests passed locally
- [✔] ✨ My changes working with up-to-date front-end and back-end part locally, like a charm
- [✔] 🔗 Link pull request to issue

2021-04-14 15:30 UTC, dmytro07 commented on src/pages/categories/category-delete/test/category-delete.test.js
> +    wrapper = mount(<CategoryDelete store={store} />);
Remove store

2021-04-14 15:31 UTC, dmytro07 commented on src/pages/categories/category-delete/test/category-delete.test.js
> +    const wrapper = mount(<CategoryDelete store={store} />);
Remove mount

2021-04-14 15:31 UTC, dmytro07 commented on src/pages/categories/category-delete/test/category-delete.test.js
> +  jest.spyOn(reactRedux, 'useDispatch');
Remove mock

2021-04-14 16:48 UTC, yuliiakucher commented on src/pages/categories/category-delete/test/category-delete.test.js
> +    jest.spyOn(reactRedux, 'useDispatch');
please remove spyOn

2021-04-19 18:44 UTC, dmytro07 submitted a review, later dismissed

2021-04-20 11:55 UTC, grebiniuk commented
CI errors should be fixed

2021-04-20 11:56 UTC, grebiniuk requested changes
CI errors should be fixed

2021-04-28 13:23 UTC, yuliiakucher approved these changes

2021-04-29 08:40 UTC, twihell approved these changes

2021-05-03 17:16 UTC, fulljsdev commented on src/pages/categories/category-delete/test/category-delete.test.js
> +import Enzyme, { mount, shallow } from 'enzyme';
shallow never used

2021-05-03 17:16 UTC, fulljsdev commented on src/pages/categories/category-delete/test/category-delete.test.js
> +    MenuItem,
MenuItem never used

2021-05-03 17:21 UTC, fulljsdev reviewed
remove unused imports

2021-05-03 17:21 UTC, fulljsdev commented on src/pages/categories/category-delete/test/category-delete.test.js
> +import { useDispatch, useSelector } from 'react-redux';
useSelector never used

2021-05-03 20:17 UTC, grebiniuk approved these changes

2021-05-03 21:21 UTC, merged