Fix/736
ita-social-projects/horondi_admin pull request #749
Opened 2021-04-28 14:49 UTC by AndronShermeta

#736 
Add responsive design for order, categories, recent changes, materials, users, users questions

#### Screenshots

Original             |  Updated
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/73708298/116422708-ad16db00-a848-11eb-90ad-855837577f41.png)
![image](https://user-images.githubusercontent.com/73708298/116422789-c4ee5f00-a848-11eb-9cad-700371330136.png)
![image](https://user-images.githubusercontent.com/73708298/116422914-dfc0d380-a848-11eb-8dbf-f8d16473d3b8.png)
![image](https://user-images.githubusercontent.com/73708298/116422987-f1a27680-a848-11eb-97ee-ecaf00c9878d.png)
![image](https://user-images.githubusercontent.com/73708298/116423042-fff09280-a848-11eb-9452-a860afa22d6a.png)
![image](https://user-images.githubusercontent.com/73708298/116423100-0bdc5480-a849-11eb-9524-0e61c930690b.png)
![image](https://user-images.githubusercontent.com/73708298/116423166-1ac30700-a849-11eb-82b3-a1a0d7f387ac.png)
![image](https://user-images.githubusercontent.com/73708298/116423258-329a8b00-a849-11eb-8fa6-5a38bcdc2e89.png)
![image](https://user-images.githubusercontent.com/73708298/116423338-447c2e00-a849-11eb-944f-891b9be0c526.png)

  |  
![image](https://user-images.githubusercontent.com/73708298/116422748-bacc6080-a848-11eb-8b06-e287ee457a59.png)
![image](https://user-images.githubusercontent.com/73708298/116422835-cf105d80-a848-11eb-8456-c412c8b4104c.png)
![image](https://user-images.githubusercontent.com/73708298/116422934-e4858780-a848-11eb-8c97-085c3a269415.png)
![image](https://user-images.githubusercontent.com/73708298/116423018-f8c98480-a848-11eb-956c-a456c222a13b.png)
![image](https://user-images.githubusercontent.com/73708298/116423066-054ddd00-a849-11eb-82cb-97a0a8cb5097.png)
![image](https://user-images.githubusercontent.com/73708298/116423128-13036280-a849-11eb-9831-11fd29766b11.png)
![image](https://user-images.githubusercontent.com/73708298/116423191-2282ab80-a849-11eb-846d-7dd12a1eb7c9.png)
![image](https://user-images.githubusercontent.com/73708298/116423222-29112300-a849-11eb-8780-4f04bbdda66c.png)
![image](https://user-images.githubusercontent.com/73708298/116423387-4f36c300-a849-11eb-86a1-c9d29f1621e1.png)

### Checklist
- [+] 🔽 My branch is up-to-date with the "development" branch
- [+] ✅ All tests passed locally
- [+] ✨ My changes working with up-to-date front-end and back-end part locally, like a charm
- [+] 🔗 Link pull request to issue

2021-05-03 17:40 UTC, fulljsdev approved these changes

2021-05-05 18:53 UTC, grebiniuk requested changes
Please try to resolve the issues we were talking about today.

2021-05-24 15:36 UTC, yuliiakucher approved these changes

2021-05-24 15:36 UTC, AndriyLymych approved these changes

2021-05-24 15:38 UTC, grebiniuk approved these changes

2021-05-24 15:38 UTC, merged