Tests/447 #447
ita-social-projects/horondi_admin pull request #769
Opened 2021-05-09 13:12 UTC by YuriiDubnytskyi

## Description
Add unit test to MaterialForm component
Add solution for jest config
#### Screenshots
![image](https://user-images.githubusercontent.com/41127730/117573491-df45f980-b0e0-11eb-9d48-fd3f1be7886c.png)
![image](https://user-images.githubusercontent.com/41127730/117573483-cccbc000-b0e0-11eb-9cf7-8873f3a7b54f.png)

### Checklist
- [x] 🔽 My branch is up-to-date with "development" branch
- [x] ✅ All tests passed locally
- [x] ✨ My changes working with up-to-date front-end and back-end part locally, like charm
- [x] 🔗 Link pull request to issue

2021-05-09 13:43 UTC, fulljsdev requested changes
Try to fix console errors
![image](https://user-images.githubusercontent.com/77093538/117574401-8fb5fc80-b0e5-11eb-9c2e-1a4ad06789e2.png)

2021-05-11 07:35 UTC, YuriiDubnytskyi commented
I tried fix but I couldn't find solution.

2021-05-24 11:21 UTC, yuliiakucher approved these changes

2021-05-24 12:08 UTC, fulljsdev approved these changes

2021-05-24 14:42 UTC, merged