Test/500
ita-social-projects/horondi_admin pull request #770
Opened 2021-05-09 14:26 UTC by sergklukvin

## Description

Write enzyme test for `MainPage` page (#500)

#### Screenshots

![1](https://user-images.githubusercontent.com/76059218/117575482-b460a300-b0ea-11eb-9d9b-e184f2d84947.jpg)

![2](https://user-images.githubusercontent.com/76059218/117575503-ca6e6380-b0ea-11eb-9756-19ff0f1ab99f.jpg)
 

### Checklist
- [ ] 🔽 My branch is up-to-date with "development" branch
- [ ] ✅ All tests passed locally
- [ ] ✨ My changes working with up-to-date front-end and back-end part locally, like charm
- [ ] 🔗 Link pull request to issue

2021-05-09 16:03 UTC, fulljsdev requested changes
many unnecessary changes
imports that have never been used
commented code

2021-05-11 11:58 UTC, yuliiakucher commented
please dont change these files
![image](https://user-images.githubusercontent.com/61886864/117811441-3971c680-b269-11eb-980c-65749ad8d44a.png)

2021-05-24 16:15 UTC, yuliiakucher approved these changes

2021-05-24 16:16 UTC, AndriyLymych approved these changes

2021-05-24 16:18 UTC, fulljsdev approved these changes

2021-05-24 16:18 UTC, merged