Test/441
ita-social-projects/horondi_admin pull request #803
Opened 2021-05-27 15:44 UTC by mvmoshchovskyi

Enzyme test for category-form

#### Screenshots

Original             |  Updated
:-------------------------:|:-------------------------:
** original screenshot **  |  ** updated screenshot **

### Checklist
- [ ] 🔽 My branch is up-to-date with "development" branch
- [ ] ✅ All tests passed locally
- [ ] ✨ My changes working with up-to-date front-end and back-end part locally, like charm
- [ ] 🔗 Link pull request to issue
![test441](https://user-images.githubusercontent.com/48692693/119856551-7ac9cd80-bf1b-11eb-8bcb-2d63c8321606.png)

2021-05-27 17:31 UTC, YuriiDubnytskyi submitted a review, later dismissed

2021-05-28 00:58 UTC, grebiniuk requested changes
Why is the coverage so low?
it should be at least 80%

2021-06-22 19:10 UTC, grebiniuk approved these changes

2021-06-22 19:10 UTC, yuliiakucher approved these changes

2021-06-22 19:11 UTC, merged