Bug fix/808
ita-social-projects/horondi_admin pull request #812
Opened 2021-06-07 10:28 UTC by sergklukvin

- Changes in routes
- Changes in  ModelForm Component
![screen2](https://user-images.githubusercontent.com/76059218/121001528-0e10c780-c794-11eb-98ce-f533672ed4c7.jpg)
![screen3](https://user-images.githubusercontent.com/76059218/121001535-0f41f480-c794-11eb-94b4-29d340d8d878.jpg)
![screen4](https://user-images.githubusercontent.com/76059218/121001536-0fda8b00-c794-11eb-807d-085ed9b064fa.jpg)

### Checklist
- [ ] 🔽 My branch is up-to-date with "development" branch
- [ ] ✅ All tests passed locally
- [ ] ✨ My changes working with up-to-date front-end and back-end part locally, like charm
- [ ] 🔗 Link pull request to issue

2021-06-10 05:55 UTC, YuriiDubnytskyi requested changes
Please fix code smell

2021-06-11 14:28 UTC, yuliiakucher approved these changes

2021-06-11 14:28 UTC, mvmoshchovskyi approved these changes

2021-06-11 14:30 UTC, YuriiDubnytskyi approved these changes

2021-06-11 14:30 UTC, merged