Bug fix/401
ita-social-projects/horondi_admin pull request #826
Opened 2021-06-17 21:31 UTC by Elugormo

## Description

1. For resolving this bug and regarding the UI part, I rebuilt the QnA details page and refactored it by completely deleting it from the source file. To implement the features mentioned in the description of my task, I used some components from Material-UI, specifically, I used the basic concept of accordion-like collapsable fields in a table. To implement the particular feature, I created a completely new component not to interfere with the parent component and basic table styling defined in table-create-like files. So by using my new Collapsable Table View component I implemented the basic collapsable table fields, with accordion-like functionality, where the Admin can write a reply to customers' questions. Also, I did a great job regarding styling and making it look good and marvellous as it possibly could be. 

2. Also, I rewrote hardcoded filters that were created for this component previously and changed them to more basic ones, that are used on several other pages and are default. I completely recreated my FilterByValue because of problematic and incorrect usage. 
3. For the in-system frontend development part, I solved some issues concerning Redux data flow and recreated a new hook to make data fetching easier and smoother. Also, I found several problems regarding pagination and solved them as well. Significant changes were made concerning GraphQl. The hardcoded filter that was built inside the query was falsy, so I did some research not only on the Frontend part but also some changes were applied to the Backend part. Consider typedefs and Filter types that I made for easy fetching, and also I got rid of hardcoded obscuring filters by replacing them with more straightforward and conceivable ones.
4. Basic implementation of the search was implemented using a basic filter navigation component with my own-coded redux actions and GraphQl queries.

#### Screenshots

Original             |  Updated
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/53963530/122435997-24433280-cfa1-11eb-9a14-b6109136763c.png)  Previous view |  ![image](https://user-images.githubusercontent.com/53963530/122436084-345b1200-cfa1-11eb-8821-aa1ef2b125e2.png) Updated View
![image](https://user-images.githubusercontent.com/53963530/122436273-5b194880-cfa1-11eb-811b-b2bbfa6e12ba.png) Old QnA details page | ![image](https://user-images.githubusercontent.com/53963530/122436339-6a989180-cfa1-11eb-8aff-27641d7864e9.png) Updated view with accordion functionality instead of using separate pages
![image](https://user-images.githubusercontent.com/53963530/122436826-ce22bf00-cfa1-11eb-87db-e6d69533271d.png) Old filters | ![image](https://user-images.githubusercontent.com/53963530/122437060-062a0200-cfa2-11eb-937b-91775453ba6c.png) Updated filters
![image](https://user-images.githubusercontent.com/53963530/122437213-2d80cf00-cfa2-11eb-97f4-06b97e18da1d.png) Old broken filter | ![image](https://user-images.githubusercontent.com/53963530/122437337-4a1d0700-cfa2-11eb-8a27-b48939984d4e.png)  New, user-friendly one
![image](https://user-images.githubusercontent.com/53963530/122437741-aaac4400-cfa2-11eb-9778-4f6f099a254e.png) No pagination provided though functionality is essential | ![image](https://user-images.githubusercontent.com/53963530/122437839-c4e62200-cfa2-11eb-9ca6-185c96a4c7dc.png) Solved issue

### Checklist
- [x] 🔽 My branch is up-to-date with "development" branch
- [x] ✅ All tests passed locally
- [x] ✨ My changes working with up-to-date front-end and back-end part locally, like charm
- [x] 🔗 Link pull request to issue

2021-06-19 22:00 UTC, grebiniuk requested changes
Please cover your functionality with tests.
There should be at least 80% coverage of the new code.

2021-06-22 12:45 UTC, Elugormo commented on src/containers/table-container-collapsable-row/table-container-collapsable-row.js
> +              inputProps={{ 'aria-label': 'checkbox with default color' }}
fixed

2021-06-22 12:45 UTC, Elugormo commented on src/containers/table-container-collapsable-row/table-container-collapsable-row.js
> +                Запитання від {properties.senderName}:
fixed

2021-06-22 12:45 UTC, Elugormo commented on src/containers/table-container-collapsable-row/table-container-collapsable-row.js
> +                    Відповідь:
fixed

2021-06-22 12:45 UTC, Elugormo commented on src/containers/table-container-collapsable-row/table-container-collapsable-row.js
> +                    label='Введіть вашу відповідь'
fixed

2021-06-22 12:45 UTC, Elugormo commented on src/containers/table-container-collapsable-row/table-container-collapsable-row.js
> +                      Відповісти
fixed

2021-06-22 12:46 UTC, Elugormo commented on src/pages/email-questions/email-questions-list.js
> +          const questionToShow = `<b>Запитання:</b> ${question.text}`;
fixed

2021-06-22 12:46 UTC, Elugormo commented on src/utils/email-question-list.js
> +  answer && answer.text ? `<br> <b>Відповідь:</b> ${answer.text}` : '';
fixed

2021-06-22 12:46 UTC, Elugormo commented on src/utils/questions.js
> +export const placeholderQuestionSearch = 'по тексту';
fixed

2021-06-23 19:25 UTC, grebiniuk approved these changes

2021-06-23 19:26 UTC, yuliiakucher approved these changes

2021-06-23 19:26 UTC, merged