Refactoring form buttons #706
ita-social-projects/horondi_admin pull request #844
Opened 2021-06-30 21:55 UTC by NetkachovaAnastasiya

Refactoring few form buttons on these pages: 
/products/add-product
/business-pages
/categories/add-category

For now, three screens are ready, please have a look if it is expected behavior.

### Checklist
- [ ] 🔽 My branch is up-to-date with "development" branch
- [ ] 🔗https://github.com/ita-social-projects/horondi_admin/issues/706

2021-07-01 10:47 UTC, sergklukvin requested changes
1. Fix code smell
2.  Add link on issue here
![1](https://user-images.githubusercontent.com/76059218/124107902-5d35d980-da6e-11eb-863c-17a0102f5dc6.jpg)

2021-07-01 15:15 UTC, mvmoshchovskyi commented
CI is Failed 
Please check tests  before push

2021-07-05 20:24 UTC, mvmoshchovskyi requested changes
fix code smells

2021-07-08 14:29 UTC, sergklukvin approved these changes

2021-07-08 14:30 UTC, mvmoshchovskyi approved these changes

2021-07-08 14:30 UTC, merged