add photos of new group members
ita-social-projects/horondi_admin pull request #855
Opened 2021-07-02 11:21 UTC by ostgit12

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

#### Screenshots
Before changes
[![@Walleriy](https://avatars.githubusercontent.com/u/39501370?s=200)](https://github.com/Walleriy)
[![@AndronShermeta](https://avatars.githubusercontent.com/u/73708298?s=200)](https://github.com/AndronShermeta)
[![@khrystynaDm1307](https://avatars.githubusercontent.com/u/53223985?s=200)](https://github.com/khrystynaDm1307)
[![@YuriiDubnytskyi](https://avatars.githubusercontent.com/u/41127730?s=200)](https://github.com/YuriiDubnytskyi)
[![@Renfort](https://avatars.githubusercontent.com/u/60984686?s=200)](https://github.com/Renfort)
[![@sergklukvin](https://avatars.githubusercontent.com/u/76059218?s=200)](https://github.com/sergklukvin)
[![@mvmoshchovskyi](https://avatars.githubusercontent.com/u/48692693?s=200)](https://github.com/mvmoshchovskyi)

After added new teams fotos links
[![@ostgit12](https://avatars.githubusercontent.com/u/56637675?s200)](https://github.com/ostgit12)
[![@100vbaSasha](https://avatars.githubusercontent.com/u/55619101?s=200)](https://github.com/100vbaSasha)
[![@Walleriy](https://avatars.githubusercontent.com/u/39501370?s=200)](https://github.com/Walleriy)
[![@AndronShermeta](https://avatars.githubusercontent.com/u/73708298?s=200)](https://github.com/AndronShermeta)
[![@YuriiDubnytskyi](https://avatars.githubusercontent.com/u/41127730?s=200)](https://github.com/YuriiDubnytskyi)
[![@Renfort](https://avatars.githubusercontent.com/u/60984686?s=200)](https://github.com/Renfort)
[![@sergklukvin](https://avatars.githubusercontent.com/u/76059218?s=200)](https://github.com/sergklukvin)
[![@mvmoshchovskyi](https://avatars.githubusercontent.com/u/48692693?s=200)](https://github.com/mvmoshchovskyi)
[![@Vlodkojr](https://avatars.githubusercontent.com/u/45718327?s=200)](https://github.com/Vlodkojr)
[![@TetianaHrunyk](https://avatars.githubusercontent.com/u/43062042?s=200)](https://github.com/TetianaHrunyk)
[![@Elugormo](https://avatars.githubusercontent.com/u/53963530?s=200)](https://github.com/Elugormo)
[![@Mabonik](https://avatars.githubusercontent.com/u/61788391?s=200)](https://github.com/Mabonik)
[![@NetkachovaAnastasiya](https://avatars.githubusercontent.com/u/60103758?s=200)](https://github.com/NetkachovaAnastasiya)
[![@Serhii-Ahafonov](https://avatars.githubusercontent.com/u/61708033?s=200)](https://github.com/Serhii-Ahafonov)
[![@Palidovych](https://avatars.githubusercontent.com/u/54260733?s=200)](https://github.com/Palidovych)

### Checklist
- [X] 🔽 My branch is up-to-date with "development" branch
- [X] ✅ All tests passed locally
- [X] ✨ My changes working with up-to-date front-end and back-end part locally, like charm
- [X] 🔗 Link pull request to issue

2021-07-02 11:52 UTC, yuliiakucher approved these changes

2021-07-02 12:23 UTC, grebiniuk requested changes
Please find out why your avatar is out of the usual size:
![image](https://user-images.githubusercontent.com/32039216/124274029-af433180-db38-11eb-8554-2ccda37f574d.png)

2021-07-06 10:45 UTC, grebiniuk approved these changes

2021-07-06 10:57 UTC, yuliiakucher approved these changes

2021-07-06 10:57 UTC, merged