Style and route in recent comments Feature/849
ita-social-projects/horondi_admin pull request #858
Opened 2021-07-03 13:03 UTC by YuriiDubnytskyi

Add style and route to recent comments
Fix delete method

![image](https://user-images.githubusercontent.com/41127730/124355093-20a5e180-dc18-11eb-9f73-8cd83898cf68.png)

### Checklist
- [x] 🔽 My branch is up-to-date with "development" branch
- [x] ✅ All tests passed locally
- [x] ✨ My changes working with up-to-date front-end and back-end part locally, like charm
- [x] 🔗 Link pull request to issue

2021-07-05 13:45 UTC, sergklukvin requested changes

2021-07-05 13:45 UTC, sergklukvin commented on src/pages/main-page/main-page.js
> +        {moment.unix(new Date(date) / 1000).format('DD.MM.YYYY ')}
please, add to utils

2021-07-06 14:39 UTC, sergklukvin approved these changes

2021-07-06 14:39 UTC, mvmoshchovskyi approved these changes

2021-07-06 14:40 UTC, merged